import type { NavLink, Project, Skill, SocialLink } from "@/types";

export const NAV_LINKS: NavLink[] = [
  { label: "Home", href: "#hero" },
  { label: "About", href: "#about" },
  { label: "Services", href: "#services" },
  { label: "Projects", href: "#projects" },
  { label: "Contact", href: "#contact" },
];

export const SOCIAL_LINKS: SocialLink[] = [
  { label: "GitHub", href: "https://github.com/hanseehhh" },
  { label: "LinkedIn", href: "#" },
  { label: "Email", href: "mailto:your@email.com" },
];

export const PROJECTS: Project[] = [
  {
    id: "project-1",
    title: "Project One",
    description: "Short description of what this project does and what problem it solves.",
    tech: ["Next.js", "TypeScript", "Tailwind CSS"],
    href: "#",
    repo: "https://github.com/hanseehhh",
    featured: true,
  },
  {
    id: "project-2",
    title: "Project Two",
    description: "Short description of what this project does and what problem it solves.",
    tech: ["React", "Node.js", "PostgreSQL"],
    href: "#",
    repo: "https://github.com/hanseehhh",
    featured: true,
  },
  {
    id: "project-3",
    title: "Project Three",
    description: "Short description of what this project does and what problem it solves.",
    tech: ["Python", "FastAPI", "Docker"],
    href: "#",
    repo: "https://github.com/hanseehhh",
  },
  {
    id: "project-4",
    title: "Project Four",
    description: "Short description of what this project does and what problem it solves.",
    tech: ["React", "TypeScript", "Firebase"],
    href: "#",
    repo: "https://github.com/hanseehhh",
  },
  {
    id: "project-5",
    title: "Project Five",
    description: "Short description of what this project does and what problem it solves.",
    tech: ["Next.js", "Prisma", "MySQL"],
    href: "#",
    repo: "https://github.com/hanseehhh",
  },
  {
    id: "project-6",
    title: "Project Six",
    description: "Short description of what this project does and what problem it solves.",
    tech: ["Vue.js", "Node.js", "MongoDB"],
    href: "#",
    repo: "https://github.com/hanseehhh",
  },
  {
    id: "project-7",
    title: "Project Seven",
    description: "Short description of what this project does and what problem it solves.",
    tech: ["React Native", "Expo", "Supabase"],
    href: "#",
    repo: "https://github.com/hanseehhh",
  },
  {
    id: "project-8",
    title: "Project Eight",
    description: "Short description of what this project does and what problem it solves.",
    tech: ["PHP", "Laravel", "MySQL"],
    href: "#",
    repo: "https://github.com/hanseehhh",
  },
  {
    id: "project-9",
    title: "Project Nine",
    description: "Short description of what this project does and what problem it solves.",
    tech: ["Python", "Django", "PostgreSQL"],
    href: "#",
    repo: "https://github.com/hanseehhh",
  },
  {
    id: "project-10",
    title: "Project Ten",
    description: "Short description of what this project does and what problem it solves.",
    tech: ["Next.js", "Tailwind CSS", "Framer Motion"],
    href: "#",
    repo: "https://github.com/hanseehhh",
  },
  {
    id: "project-11",
    title: "Project Eleven",
    description: "Short description of what this project does and what problem it solves.",
    tech: ["React", "Redux", "Node.js"],
    href: "#",
    repo: "https://github.com/hanseehhh",
  },
  {
    id: "project-12",
    title: "Project Twelve",
    description: "Short description of what this project does and what problem it solves.",
    tech: ["TypeScript", "Express", "Docker"],
    href: "#",
    repo: "https://github.com/hanseehhh",
  },
];

export const SKILLS: Skill[] = [
  { name: "TypeScript", category: "frontend" },
  { name: "React", category: "frontend" },
  { name: "Next.js", category: "frontend" },
  { name: "Tailwind CSS", category: "frontend" },
  { name: "Framer Motion", category: "frontend" },
  { name: "ReactBits", category: "frontend" },
  { name: "Dart", category: "frontend" },
  { name: "Node.js", category: "backend" },
  { name: "Next.js", category: "backend" },
  { name: "MySQL", category: "backend" },
  { name: "PHP", category: "backend" },
  { name: "PostgreSQL", category: "backend" },
  { name: "Python", category: "backend" },
  { name: "Git", category: "tools" },
  { name: "Docker", category: "tools" },
  { name: "Figma", category: "tools" },
];
